.PHONY: help up down build logs restart clean migrate migrate-down revision seed backend-shell db-shell test

help:
	@echo "GitHub Time Machine — common commands"
	@echo ""
	@echo "  make up             Start all services (db, backend, frontend)"
	@echo "  make down           Stop all services"
	@echo "  make build          Rebuild all images"
	@echo "  make logs           Tail logs from all services"
	@echo "  make restart        Restart backend + frontend (keep db running)"
	@echo "  make clean          Stop services AND wipe volumes (db data, repo clones)"
	@echo ""
	@echo "  make migrate        Apply all pending Alembic migrations"
	@echo "  make migrate-down   Roll back the last migration"
	@echo "  make revision msg='add foo column'   Generate a new autogenerated migration"
	@echo ""
	@echo "  make seed           Populate the DB with a demo repository analysis"
	@echo "  make backend-shell  Open a shell inside the backend container"
	@echo "  make db-shell       Open a psql shell inside the db container"
	@echo "  make test           Run backend test suite"

up:
	docker compose up --build

down:
	docker compose down

build:
	docker compose build --no-cache

logs:
	docker compose logs -f

restart:
	docker compose restart backend frontend

clean:
	docker compose down -v
	@echo "Volumes wiped: postgres_data, repo_clones"

migrate:
	docker compose exec backend alembic upgrade head

migrate-down:
	docker compose exec backend alembic downgrade -1

revision:
	docker compose exec backend alembic revision --autogenerate -m "$(msg)"

seed:
	docker compose exec backend python scripts/seed_demo.py

backend-shell:
	docker compose exec backend /bin/bash

db-shell:
	docker compose exec db psql -U postgres -d github_time_machine

test:
	docker compose exec backend pytest -v
